workflows:
  ios-release:
    name: MindSteps iOS

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - flutter clean
      - flutter pub get
      - cd ios && pod install && cd ..
      - flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/Runner.app